### PR TITLE
Update hardcoded company name

### PR DESCRIPTION
**Pull request by gponsu**

### CODE REVIEW

**Comment by scruti** [comment]
:+1:

**Comment by Fernan2** [comment]
The company is not Verema S.L., but Verema Interactiva S.L., as you can see in the footer... so I guess that you'll need either add another parameter in `Personalizacion` (lib/news_tematica.rb) or declare a new constant on the main apps...

(I prefer the first option).

**Comment by d2bit** [comment]
It seems tests don't know about `ESTA_WEB` add it to dummy
 :+1:

**Comment by scruti** [comment]
:+1:

**Comment by maxvlc** [comment]
:+1:

**Comment by gponsu** [comment]
@Fernan2 mergeit?

**Comment by Fernan2** [comment]
The new value should be provided on `test/dummy/config/initializers/engines.rb`

(of course, both Rankia & Verema should also include the new parameter when calling to this version)

**Pull request merged**
