### PR TITLE
Add fecha fields on edit

### PR DESCRIPTION
**Pull request by d2bit**
[task](https://trello.com/c/PidQ1Kbi/985-v-no-funciona-el-automatismo-en-las-news-de-verema)

### CODE REVIEW

**Comment by Fernan2** [comment]
How those dates get saved? I think that changing the dates and then going to select contenidos will show the contenidos in the old range...

**Comment by d2bit** [comment]
what do you mean? @Fernan2

**Comment by d2bit** [comment]
captura de pantalla de 2016-01-12 12-21-10

@Fernan2 do you like it? I do :sweat_smile:

**Comment by 007lva** [comment]
:+1:

**Comment by Fernan2** [comment]
Great! :+1:

**Pull request merged**
